cc_test(
    name = 'json_read_test',
    srcs = 'json_read_test.cc',
    deps = [
        '//thirdparty/gtest:gtest',
        '//thirdparty/jsoncpp:jsoncpp',
    ],
    testdata = [
        './conf'
    ]
)