/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"git@github.com:Lohnwave/thirdparty.git\n"
"* master\n"
"commit df93eeed64336b0a70248d990f74dbc24e0758a4\n"
"Author: CHEN Feng <chen3feng@gmail.com>\n"
"Date:   Thu Jan 17 12:10:01 2019 -0500\n"
"\n"
"    Add autotools.bld\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Fri Nov 27 20:29:12 2020";
extern const char kBuilderName[] = "luozu";
extern const char kHostName[] = "luozu-K45VD";
extern const char kCompiler[] = "GCC 7";
}}
